use std::path::PathBuf;

use clap::{Parser, ValueEnum, command};

/// Command-line utility to parse and analyse csv files generated by Stripe.
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
pub struct Args {
    /// Path to the csv file to analyse
    pub file: PathBuf,

    /// Type of csv file to analyse
    pub csv_type: CsvType,

    /// Optional output file to write the analysis results to, default to the input filename + _out.csv
    #[arg(short, long)]
    pub output_file: Option<PathBuf>,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, ValueEnum)]
pub enum CsvType {
    /// Application fees analysis
    Fees,
}
